version: '3.9'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/nest
    volumes:
      - .:/home/app
      - /home/app/node_modules
    command: npm run start:prod

  mongo:
    image: mongo:8
    container_name: mongo-db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
